public class BuddyInfo extends AddressBook{

    //Methods generated by intelliJ
    public String getName() {
        return name;
    }

    public String getAddress() {
        return address;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    //constructor
    BuddyInfo(String gname, String gaddress, String gphoneNum){
        name=gname;
        address=gaddress;
        phoneNum=gphoneNum;
    }

    //Variables
    private String name;
    private String address;
    private String phoneNum;

    //main
    public static void main(String[] args) {
        System.out.println("Hello World!");

        BuddyInfo friend=new BuddyInfo("Royce", "123 LMAO ave NE", "613 123 4567");
        System.out.println("Hello "+friend.getName());
    }
}
